name: Publish

on: 
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Pack
      run: dotnet pack --no-build -c Release
    - name: Upload NuGet package
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@main
      with:
        name: dotnet-interactive-ilkernel
        path: artifacts/bin/Release/DotNet.Interactive.Extensions.ILKernel/*.nupkg
        if-no-files-found: error